yarnPath: .yarn/releases/yarn-3.3.1.cjs

packageExtensions:
  "@storybook/cli@*":
    dependencies:
      react: "*"
      react-dom: "*"
  "@storybook/core-common@*":
    dependencies:
      react: "*"
      react-dom: "*"
      "@storybook/react-webpack5": "^7.0.0-beta"
  "@storybook/preset-react-webpack@*":
    dependencies:
      webpack: "*"
      react-dom: "*"
